packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  vue: ^3.5.13
  typescript: ^5.7.2
  vite: ^6.0.7
  unplugin-vue: ^6.0.0
  vite-plugin-dts: ^4.4.1
  vue-tsc: ^2.2.0
  '@types/node': ^22.10.5
  vitest: ^3.0.5
  happy-dom: ^15.11.7
