packages:
  - packages/*
  - apps/*

catalog:
  '@types/node': ^22.10.5
  happy-dom: ^20.5.0
  typescript: ^5.7.2
  unplugin-vue: ^6.0.0
  vite: ^6.0.7
  vite-plugin-dts: ^4.4.1
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-tsc: ^2.2.0
